import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar.tsx'
import Hero from '../components/hero.tsx'
import { useWeb3 } from '@3rdweb/hooks'
import metaSpace from '../assets/opensea.png'
import { client } from '../lib/sanityClient.ts'
import toast, { Toaster } from 'react-hot-toast'

const style = {
  wrapper: `relative`,
  container: `before:content-[''] before:bg-red-500 before:absolute before:top-0 before:left-0 before:right-0 before:bottom-0 before:bg-[url('https://lh3.googleusercontent.com/ujepnqpnL0nDQIHsWxlCXzyw4pf01yjz1Jmb4kAQHumJAPrSEj0-e3ABMZlZ1HEpJoqwOcY_kgnuJGzfXbd2Tijri66GXUtfN2MXQA=s250')] before:bg-cover before:bg-center before:opacity-30 before:blur`,
  contentWrapper: `flex h-screen relative justify-center flex-wrap items-center`,
  title: `relative text-white text-[46px] font-semibold`,
  description: `text-[#8a939b] container-[400px] text-2xl mt-[0.8rem] mb-[2.5rem] flex justify-center`,
  ctaContainer: `flex justify-center items-center`,
  accentedButton: ` relative text-lg font-semibold px-12 py-4 bg-[#2181e2] rounded-lg mr-5 text-white hover:bg-[#42a0ff] cursor-pointer`,
  button: ` relative text-lg font-semibold px-12 py-4 bg-[#363840] rounded-lg mr-5 text-[#e4e8ea] hover:bg-[#4c505c] cursor-pointer`,
}

export default function Home() {
  const { address, connectWallet } = useWeb3()

  const welcomeUser = (userName, toastHandler = toast) => {
    toastHandler.success(
      `Welcome back ${userName != 'Unnamed' ? `${userName}` : ''}!`, {
      position: "bottom-center",
      style: {
        border : "1px solid #2181e2",
        background: 'transparent',
        filter: blur(4),
        color: '#fff',
      },
    })    
  }
  useEffect(() => {
    if (!address) return
    //immediately involked function : IITFE
      ;(async () => {
        const userDoc = {
          _type: 'users',
          _id: address,
          userName: 'Unnamed',
          walletAddress: address,
        }
        const user = await client.createIfNotExists(userDoc)

        welcomeUser(user.UserName)
      })()
    }, [address])
    ;(() => console.log('hello'))()
  
  return (
    <div className={styles.wrapper}>
      <Toaster />
      {address ? (
        <>
           <Head>
             <title>Create Next App</title>
             <meta name="description" content="Generated by create next app" />
             <link rel="icon" href="/favicon.ico" />
           </Head>
           <NavBar />
           <Hero /> 
        </>
      ) : (
        <div className={style.wrapper}>
        <div className={style.container}>
          <div className={style.contentWrapper}>
            <div className={style.copyContainer}>
              <div className={style.ctaContainer}>
                <button 
                  className={style.accentedButton}
                  onClick={() => connectWallet('injected')}
                >Connect Wallet</button>
              </div>
              <div className={style.description}>
              Make sure to install MetaMask extension ;)
              </div>
            </div>
          </div>
        </div>
      </div>
      )}
    </div>
  )
}
